apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: kiwi-tcms
spec:
  selector:
    app: kiwi-tcms
    tier: frontend
  type: LoadBalancer
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
    - name: "443"
      port: 443
      targetPort: 8443
